### ISSUE TITLE
«huaq»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#18]
"huaq": {
      "official": {
        "english": "▯ is more the case than ▯; ▯ is more than ▯ in property ▯.",
        "gloss": "more"
      },
      "frame": "c c 1"
    }

@acotis input ‘c c 1’; I double-checked his ‘frame-list.txt’ document and there's no mention of ‘0 0; c c 1’ type which the English definitely suggests. What shall we do?

**Comment by solpahi** [comment]
Always remember that the type signature does not necessarily tell you whether a place applies to a proposition or a concrete thing. The signature only tells you how the places combine in serial predicates. 

huaq/2 talks about two propositions, but whether it is (c c) or has a 0-place somewhere depends on whether we want it to subordinate in serials. Since I think the answer is no, the correct signature should be [(c) (c c) (c c 1)], which is what it is currently listed as.

**Comment by ciuak** [comment]
> Always remember.

Roger.

**Comment by acotis** [comment]
Come to think of it, it's a moot point anyway, because only the maximal arity ever has a shot at combining.

...unless we want to allow things like **lỉ hủaq ja dó ja dó na pảı**

**Comment by ciuak** [comment]
Agreed – I should've thought it through before I posted, @acotis. (It was late at night, so forgive me.)
Perhaps sheer purity should tell us that, in the absence of a slot to draw from the child predicate in a serial, we should allow the ‘0 0’ case to activate. For example, if «hao» is /0, we'd have
> «hủaq hảo hâohāo»
> ‘Better than that hao is that haohāo.’

It's a pretty useless use case, of course.
