### ISSUE TITLE
github page for the dictionary

### ISSUE THREAD

**Issue by solpahi** [toaq/dictionary#75]
As `dictionary.json` is meant to replace toaq.org/dictionary, it would be good to have a readable version of it at toaq.github.io/dictionary.

**Comment by uakci** [comment]
The HTML file generation process itself is ready; the problem lies within how we'd actually *get* the generated file into the repository every time a change is made. I see there being three options:

1. Every time a change is made, the committer regenerates the HTML file and adds it to their commit. (Yeah, good luck with that);
2. A bot commits the HTML (which would yield a lot of commit fluff);
3. We set up and organize around releases, and the releaser pushes the HTML file.

(3) seems to be the best option out of the three, but it would actually require us to burn through the issue backlog. As always, @solpahi, your judgement is needed to proceed with any one of the options.

**Comment by solpahi** [comment]
Pardon my ignorance, but couldn't the same method we use to generate the TwE pages be used for the dictionary page? When someone changes `dictionary.json` the html gets generated automatically. I don't know if that's (2) in your list. (1) sounds bad and (3) I don't understand, but it sounds more complicated than my suggestion. If it works for TwE, why not for the dictionary?

**Comment by uakci** [comment]
The GitHub-provided feature that we're using for TwE is one that, instead of serving the files on the repository, passes them on to Jekyll (a static site/blog generation suite which supports Markdown) and has GitHub serve *its* output at the something.github.io address. This feature is non-extensible and its extent is Markdown conversion.

We *could* have the HTML auto-(re)generate, but the output would not be able to go to the github.io website, only e.g. on my servers. (2) is the same, except that the process results in another commit atop yours (*not* a good idea!).

(3) means that work is done on a separate branch, and once a large enough chunk of work gets done (or a release goal is met, should we set up any), the branch is merged with the main branch and the person responsible for the release generates the HTML manually.
