### ISSUE TITLE
«choq»

### ISSUE THREAD

**Issue by uakci** [toaq/dictionary#8]
"choq": {
      "official": {
        "english": "▯ uses ▯ for ▯.",
        "gloss": "use"
      },
      "frame": "c c 1"
    }

Either the frame is incorrect (‘c c 0’) or the definition should read ‘[…] for satisfying property ▯.’

**Comment by solpahi** [comment]
The key question is whether the tool has to appear in the property or not.

Strictly speaking, if you use something to achieve a task, then that tool must be in some way involved, but it may not be practical to always demand a relation.

"I use a spoon to eat my meal" -> "I use make the spoon carry my meal to my mouth" (very roughly)

I really don't know what's best here, (c c 1) or (c c 2). (c c 0) is possible, but not desirable. It would be akin to having **leo**<sub>2</sub> be a 0.

**Comment by ciuak** [comment]
I believe that it definitely has to be ‘c c 1.’ Purity would tell us we need ‘c c 2,’ but in this case, pragmatics prevail: «choq chủq» shouldn't mean ‘to use something in order to eat *it* (the thing one is using)’…
On another note, we could allow the abstraction at choq<sub>3</sub> to be either a property or a relation. A kind of optional argument, if you prefer.

**Comment by lynn** [comment]
It's `c c 1` now so I'm closing this 👍
